/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PersonaRouteImport } from './routes/persona'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CognitiveRouteImport } from './routes/cognitive'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaRoute = PersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveRoute = CognitiveRouteImport.update({
  id: '/cognitive',
  path: '/cognitive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/persona': typeof PersonaRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/persona': typeof PersonaRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/persona': typeof PersonaRoute
  '/risk': typeof RiskRoute
  '/signup': typeof SignupRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cognitive'
    | '/learn'
    | '/login'
    | '/mentor'
    | '/persona'
    | '/risk'
    | '/signup'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cognitive'
    | '/learn'
    | '/login'
    | '/mentor'
    | '/persona'
    | '/risk'
    | '/signup'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/cognitive'
    | '/learn'
    | '/login'
    | '/mentor'
    | '/persona'
    | '/risk'
    | '/signup'
    | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CognitiveRoute: typeof CognitiveRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  PersonaRoute: typeof PersonaRoute
  RiskRoute: typeof RiskRoute
  SignupRoute: typeof SignupRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona': {
      id: '/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive': {
      id: '/cognitive'
      path: '/cognitive'
      fullPath: '/cognitive'
      preLoaderRoute: typeof CognitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CognitiveRoute: CognitiveRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  PersonaRoute: PersonaRoute,
  RiskRoute: RiskRoute,
  SignupRoute: SignupRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
